spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev # 指定开发环境配置

mybatis:
  type-aliases-package: com.star.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png




